name: Build and Run Tests
on:
  push:
    branches:
    - 3.x
    - 2.x
    - "2.19"
  pull_request:
    branches:
    - 3.x
    - 2.x
    - "2.19"
permissions:
  contents: read

jobs:
  build:
    runs-on: 'ubuntu-22.04'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17', '21', '23']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      run: ./mvnw -V -B -ff -ntp verify
