name: Build and Run Tests
on:
  push:
    branches:
    - 3.x
    - 2.x
    - "2.19"
  pull_request:
    branches:
    - 3.x
    - 2.x
    - "2.19"
  # Also run once per day anyway, at 10:00 UTC (18:00 PT)
  schedule:
    - cron: "0 10 * * *"
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: ['17', '21', '23']
        os: ['ubuntu-22.04']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      run: ./mvnw -V -B -ff -ntp verify
